on:
  # push:
  schedule:
    # 16:00 UTC <==> 00:00(next day) GMT +08:00
    - cron:  '30 16 * * *'  

jobs:
  create_leetcode_daily_practice_issue:
    runs-on: ubuntu-latest
    name: create daily practice issue
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create daily practice issue action step
        uses: xingorg1/leetcode-daily-practice-action@1.3.0
        with:
          token: ${{secrets.TOKEN}}
